apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sealed-secret
  namespace: sealed-demo
spec:
  encryptedData:
    DB_PASSWORD: AgBwSfmLUwlWsvlWz468n6kmfgyi7Gte7ugtJwmfXUYko0/I3iAH/jvUervPyImUei8XY410opj/+sCQJu2mZn2+hsl7mhzwJiyeEm+k0h/qpB5Fv3ymuHdLnNVkzNxkbVaNheluKTd5Lii59fiKzgyPr/MhgqrdWlDh9dgSdhHBX2Kk69svxfucBci5Oxc4DAKTjS9THlYKGxH6irsGEb98SYHYcvUrqv8PjxcDyvprGT5SQ9gHDfZiplH99Zy9xOdcZjN20u1I4/3vi728cs9PSLjUuVfP1fr1HkVwFAKo6+qVdmdukYX8k2S7k84M4VZPZagjvfeNGjVQtWHSG33sxCLYqd0H8EKdgHPQU4P4U/A/xzgOMi0RH9Z6kBgj9BVqjWOi9Su4GLD5TUdkQ7u/yRvjY1GGanDTfXnNCWfA60qvNwMYwwz4sLs/3N7GrO55yAYH36V4ruCOUon96QYV3J/T5Gl7dF/MWFj2QumTJRSgtEXJvDp+CPyHy9CKzHUcGlvxADlWOjqKu4Y0dbGnutshwbPlPBgoiOr0iA0U7ktQyuLxocL9KwNYvwl+fJnGzYIxRubH/Zr2fD5iy7gvhhbHR5dJ2bJEeXAwKRTpixeU0tbXunzxrNgrNOcrcX6VNL8IBCvJ+NC7Ouh7gHbZOpVgTzSZ6NdYoYFKd96MbuLM0Tp/8L4TbHqzWab4knc0ZctI4CQoPrpZ9Q==
  template:
    metadata:
      creationTimestamp: null
      name: sealed-secret
      namespace: sealed-demo

