---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-password-from-parameter-store
  namespace: default
spec:
  #refreshInterval: "0" : Will not update new value from ExternalSecret provider. 
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: db-password-from-parameter-store
    creationPolicy: Owner
  data:
  - secretKey: MYSQL_ROOT_PASSWORD
    remoteRef:
      key: /demo/db_password

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-password-from-secrets-manager
  namespace: default
spec:
  #refreshInterval: "0" : Will not update new value from ExternalSecret provider. 
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: db-password-from-secrets-manager
    creationPolicy: Owner
  data:
  - secretKey: MYSQL_ROOT_PASSWORD
    remoteRef:
      key: demo/db_password
      property: db_password 
